#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SEGUEME")]
public partial class Sistema_OrcamentoDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertEQUIPE(EQUIPE instance);
  partial void UpdateEQUIPE(EQUIPE instance);
  partial void DeleteEQUIPE(EQUIPE instance);
  partial void InsertSEGUIDOR(SEGUIDOR instance);
  partial void UpdateSEGUIDOR(SEGUIDOR instance);
  partial void DeleteSEGUIDOR(SEGUIDOR instance);
  partial void InsertSEGUIDOREQUIPE(SEGUIDOREQUIPE instance);
  partial void UpdateSEGUIDOREQUIPE(SEGUIDOREQUIPE instance);
  partial void DeleteSEGUIDOREQUIPE(SEGUIDOREQUIPE instance);
  #endregion
	
	public Sistema_OrcamentoDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SEGUEMEConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Sistema_OrcamentoDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Sistema_OrcamentoDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Sistema_OrcamentoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Sistema_OrcamentoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<EQUIPE> EQUIPEs
	{
		get
		{
			return this.GetTable<EQUIPE>();
		}
	}
	
	public System.Data.Linq.Table<SEGUIDOR> SEGUIDORs
	{
		get
		{
			return this.GetTable<SEGUIDOR>();
		}
	}
	
	public System.Data.Linq.Table<SEGUIDOREQUIPE> SEGUIDOREQUIPEs
	{
		get
		{
			return this.GetTable<SEGUIDOREQUIPE>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EQUIPE")]
public partial class EQUIPE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idEquipe;
	
	private string _nome;
	
	private string _status;
	
	private EntitySet<SEGUIDOREQUIPE> _SEGUIDOREQUIPEs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEquipeChanging(int value);
    partial void OnidEquipeChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public EQUIPE()
	{
		this._SEGUIDOREQUIPEs = new EntitySet<SEGUIDOREQUIPE>(new Action<SEGUIDOREQUIPE>(this.attach_SEGUIDOREQUIPEs), new Action<SEGUIDOREQUIPE>(this.detach_SEGUIDOREQUIPEs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEquipe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idEquipe
	{
		get
		{
			return this._idEquipe;
		}
		set
		{
			if ((this._idEquipe != value))
			{
				this.OnidEquipeChanging(value);
				this.SendPropertyChanging();
				this._idEquipe = value;
				this.SendPropertyChanged("idEquipe");
				this.OnidEquipeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100)")]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EQUIPE_SEGUIDOREQUIPE", Storage="_SEGUIDOREQUIPEs", ThisKey="idEquipe", OtherKey="idEquipe")]
	public EntitySet<SEGUIDOREQUIPE> SEGUIDOREQUIPEs
	{
		get
		{
			return this._SEGUIDOREQUIPEs;
		}
		set
		{
			this._SEGUIDOREQUIPEs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SEGUIDOREQUIPEs(SEGUIDOREQUIPE entity)
	{
		this.SendPropertyChanging();
		entity.EQUIPE1 = this;
	}
	
	private void detach_SEGUIDOREQUIPEs(SEGUIDOREQUIPE entity)
	{
		this.SendPropertyChanging();
		entity.EQUIPE1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEGUIDOR")]
public partial class SEGUIDOR : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idSeguidor;
	
	private string _nome;
	
	private string _endereco;
	
	private string _email;
	
	private string _fone;
	
	private System.Nullable<System.DateTime> _aniversario;
	
	private string _nomeCirculo;
	
	private string _padrinhos;
	
	private string _anoSegueMe;
	
	private string _paroquia;
	
	private string _coordenadorJovem;
	
	private string _status;
	
	private EntitySet<SEGUIDOREQUIPE> _SEGUIDOREQUIPEs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSeguidorChanging(int value);
    partial void OnidSeguidorChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfoneChanging(string value);
    partial void OnfoneChanged();
    partial void OnaniversarioChanging(System.Nullable<System.DateTime> value);
    partial void OnaniversarioChanged();
    partial void OnnomeCirculoChanging(string value);
    partial void OnnomeCirculoChanged();
    partial void OnpadrinhosChanging(string value);
    partial void OnpadrinhosChanged();
    partial void OnanoSegueMeChanging(string value);
    partial void OnanoSegueMeChanged();
    partial void OnparoquiaChanging(string value);
    partial void OnparoquiaChanged();
    partial void OncoordenadorJovemChanging(string value);
    partial void OncoordenadorJovemChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public SEGUIDOR()
	{
		this._SEGUIDOREQUIPEs = new EntitySet<SEGUIDOREQUIPE>(new Action<SEGUIDOREQUIPE>(this.attach_SEGUIDOREQUIPEs), new Action<SEGUIDOREQUIPE>(this.detach_SEGUIDOREQUIPEs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeguidor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idSeguidor
	{
		get
		{
			return this._idSeguidor;
		}
		set
		{
			if ((this._idSeguidor != value))
			{
				this.OnidSeguidorChanging(value);
				this.SendPropertyChanging();
				this._idSeguidor = value;
				this.SendPropertyChanged("idSeguidor");
				this.OnidSeguidorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100)")]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(100)")]
	public string endereco
	{
		get
		{
			return this._endereco;
		}
		set
		{
			if ((this._endereco != value))
			{
				this.OnenderecoChanging(value);
				this.SendPropertyChanging();
				this._endereco = value;
				this.SendPropertyChanged("endereco");
				this.OnenderecoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fone", DbType="VarChar(100)")]
	public string fone
	{
		get
		{
			return this._fone;
		}
		set
		{
			if ((this._fone != value))
			{
				this.OnfoneChanging(value);
				this.SendPropertyChanging();
				this._fone = value;
				this.SendPropertyChanged("fone");
				this.OnfoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aniversario", DbType="Date")]
	public System.Nullable<System.DateTime> aniversario
	{
		get
		{
			return this._aniversario;
		}
		set
		{
			if ((this._aniversario != value))
			{
				this.OnaniversarioChanging(value);
				this.SendPropertyChanging();
				this._aniversario = value;
				this.SendPropertyChanged("aniversario");
				this.OnaniversarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCirculo", DbType="VarChar(100)")]
	public string nomeCirculo
	{
		get
		{
			return this._nomeCirculo;
		}
		set
		{
			if ((this._nomeCirculo != value))
			{
				this.OnnomeCirculoChanging(value);
				this.SendPropertyChanging();
				this._nomeCirculo = value;
				this.SendPropertyChanged("nomeCirculo");
				this.OnnomeCirculoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_padrinhos", DbType="VarChar(100)")]
	public string padrinhos
	{
		get
		{
			return this._padrinhos;
		}
		set
		{
			if ((this._padrinhos != value))
			{
				this.OnpadrinhosChanging(value);
				this.SendPropertyChanging();
				this._padrinhos = value;
				this.SendPropertyChanged("padrinhos");
				this.OnpadrinhosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoSegueMe", DbType="VarChar(100)")]
	public string anoSegueMe
	{
		get
		{
			return this._anoSegueMe;
		}
		set
		{
			if ((this._anoSegueMe != value))
			{
				this.OnanoSegueMeChanging(value);
				this.SendPropertyChanging();
				this._anoSegueMe = value;
				this.SendPropertyChanged("anoSegueMe");
				this.OnanoSegueMeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paroquia", DbType="VarChar(100)")]
	public string paroquia
	{
		get
		{
			return this._paroquia;
		}
		set
		{
			if ((this._paroquia != value))
			{
				this.OnparoquiaChanging(value);
				this.SendPropertyChanging();
				this._paroquia = value;
				this.SendPropertyChanged("paroquia");
				this.OnparoquiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coordenadorJovem", DbType="VarChar(100)")]
	public string coordenadorJovem
	{
		get
		{
			return this._coordenadorJovem;
		}
		set
		{
			if ((this._coordenadorJovem != value))
			{
				this.OncoordenadorJovemChanging(value);
				this.SendPropertyChanging();
				this._coordenadorJovem = value;
				this.SendPropertyChanged("coordenadorJovem");
				this.OncoordenadorJovemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEGUIDOR_SEGUIDOREQUIPE", Storage="_SEGUIDOREQUIPEs", ThisKey="idSeguidor", OtherKey="idSeguidor")]
	public EntitySet<SEGUIDOREQUIPE> SEGUIDOREQUIPEs
	{
		get
		{
			return this._SEGUIDOREQUIPEs;
		}
		set
		{
			this._SEGUIDOREQUIPEs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_SEGUIDOREQUIPEs(SEGUIDOREQUIPE entity)
	{
		this.SendPropertyChanging();
		entity.SEGUIDOR = this;
	}
	
	private void detach_SEGUIDOREQUIPEs(SEGUIDOREQUIPE entity)
	{
		this.SendPropertyChanging();
		entity.SEGUIDOR = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEGUIDOREQUIPE")]
public partial class SEGUIDOREQUIPE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idSeguidorEquipe;
	
	private System.Nullable<int> _idSeguidor;
	
	private System.Nullable<int> _idEquipe;
	
	private string _ano;
	
	private string _paroquia;
	
	private string _status;
	
	private string _funcao;
	
	private string _equipe;
	
	private EntityRef<EQUIPE> _EQUIPE1;
	
	private EntityRef<SEGUIDOR> _SEGUIDOR;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSeguidorEquipeChanging(int value);
    partial void OnidSeguidorEquipeChanged();
    partial void OnidSeguidorChanging(System.Nullable<int> value);
    partial void OnidSeguidorChanged();
    partial void OnidEquipeChanging(System.Nullable<int> value);
    partial void OnidEquipeChanged();
    partial void OnanoChanging(string value);
    partial void OnanoChanged();
    partial void OnparoquiaChanging(string value);
    partial void OnparoquiaChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnfuncaoChanging(string value);
    partial void OnfuncaoChanged();
    partial void OnequipeChanging(string value);
    partial void OnequipeChanged();
    #endregion
	
	public SEGUIDOREQUIPE()
	{
		this._EQUIPE1 = default(EntityRef<EQUIPE>);
		this._SEGUIDOR = default(EntityRef<SEGUIDOR>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeguidorEquipe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idSeguidorEquipe
	{
		get
		{
			return this._idSeguidorEquipe;
		}
		set
		{
			if ((this._idSeguidorEquipe != value))
			{
				this.OnidSeguidorEquipeChanging(value);
				this.SendPropertyChanging();
				this._idSeguidorEquipe = value;
				this.SendPropertyChanged("idSeguidorEquipe");
				this.OnidSeguidorEquipeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeguidor", DbType="Int")]
	public System.Nullable<int> idSeguidor
	{
		get
		{
			return this._idSeguidor;
		}
		set
		{
			if ((this._idSeguidor != value))
			{
				if (this._SEGUIDOR.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidSeguidorChanging(value);
				this.SendPropertyChanging();
				this._idSeguidor = value;
				this.SendPropertyChanged("idSeguidor");
				this.OnidSeguidorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEquipe", DbType="Int")]
	public System.Nullable<int> idEquipe
	{
		get
		{
			return this._idEquipe;
		}
		set
		{
			if ((this._idEquipe != value))
			{
				if (this._EQUIPE1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidEquipeChanging(value);
				this.SendPropertyChanging();
				this._idEquipe = value;
				this.SendPropertyChanged("idEquipe");
				this.OnidEquipeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="VarChar(100)")]
	public string ano
	{
		get
		{
			return this._ano;
		}
		set
		{
			if ((this._ano != value))
			{
				this.OnanoChanging(value);
				this.SendPropertyChanging();
				this._ano = value;
				this.SendPropertyChanged("ano");
				this.OnanoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paroquia", DbType="VarChar(100)")]
	public string paroquia
	{
		get
		{
			return this._paroquia;
		}
		set
		{
			if ((this._paroquia != value))
			{
				this.OnparoquiaChanging(value);
				this.SendPropertyChanging();
				this._paroquia = value;
				this.SendPropertyChanged("paroquia");
				this.OnparoquiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_funcao", DbType="VarChar(100)")]
	public string funcao
	{
		get
		{
			return this._funcao;
		}
		set
		{
			if ((this._funcao != value))
			{
				this.OnfuncaoChanging(value);
				this.SendPropertyChanging();
				this._funcao = value;
				this.SendPropertyChanged("funcao");
				this.OnfuncaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipe", DbType="VarChar(100)")]
	public string equipe
	{
		get
		{
			return this._equipe;
		}
		set
		{
			if ((this._equipe != value))
			{
				this.OnequipeChanging(value);
				this.SendPropertyChanging();
				this._equipe = value;
				this.SendPropertyChanged("equipe");
				this.OnequipeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EQUIPE_SEGUIDOREQUIPE", Storage="_EQUIPE1", ThisKey="idEquipe", OtherKey="idEquipe", IsForeignKey=true)]
	public EQUIPE EQUIPE1
	{
		get
		{
			return this._EQUIPE1.Entity;
		}
		set
		{
			EQUIPE previousValue = this._EQUIPE1.Entity;
			if (((previousValue != value) 
						|| (this._EQUIPE1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._EQUIPE1.Entity = null;
					previousValue.SEGUIDOREQUIPEs.Remove(this);
				}
				this._EQUIPE1.Entity = value;
				if ((value != null))
				{
					value.SEGUIDOREQUIPEs.Add(this);
					this._idEquipe = value.idEquipe;
				}
				else
				{
					this._idEquipe = default(Nullable<int>);
				}
				this.SendPropertyChanged("EQUIPE1");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEGUIDOR_SEGUIDOREQUIPE", Storage="_SEGUIDOR", ThisKey="idSeguidor", OtherKey="idSeguidor", IsForeignKey=true)]
	public SEGUIDOR SEGUIDOR
	{
		get
		{
			return this._SEGUIDOR.Entity;
		}
		set
		{
			SEGUIDOR previousValue = this._SEGUIDOR.Entity;
			if (((previousValue != value) 
						|| (this._SEGUIDOR.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SEGUIDOR.Entity = null;
					previousValue.SEGUIDOREQUIPEs.Remove(this);
				}
				this._SEGUIDOR.Entity = value;
				if ((value != null))
				{
					value.SEGUIDOREQUIPEs.Add(this);
					this._idSeguidor = value.idSeguidor;
				}
				else
				{
					this._idSeguidor = default(Nullable<int>);
				}
				this.SendPropertyChanged("SEGUIDOR");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
